question_data = {
    "response_code": 0,
    "results": [
        {
            "category": "Animals",
            "type": "boolean",
            "difficulty": "medium",
            "question": "An octopus can fit through any hole larger than its beak.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Celebrities",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the first music video to broadcast on MTV.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "French is an official language in Canada.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Linus Torvalds created Linux and Git.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Mathematics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The &#039;Squaring the Circle&#039; problem is solvable.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Studio Ghibli is a Japanese animation studio responsible for the films &quot;Wolf Children&quot; and &quot;The Boy and the Beast&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Gothenburg is the capital of Sweden.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "You can legally drink alcohol while driving in Mississippi.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Sonoran Desert is located in eastern Africa.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Gadgets",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "medium",
            "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Liechtenstein does not have an airport.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "medium",
            "question": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Undertale&quot;, the main character of the game is Sans.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Klingons respect their disabled comrades, and those who are old, injuried, and helpless.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Television",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An average human can go two weeks without water.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Mathematics",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The set of all algebraic numbers is countable.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Cartoon & Animations",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Waylon Smithers from &quot;The Simpsons&quot; was originally black when he first appeared in the series.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Fiat Multipla is a drivable car in &quot;Forza Horizon 3&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Mathematics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The sum of any two odd integers is odd.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat meat.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Vehicles",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The majority of Subaru vehicles are made in China.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Sound can travel through a vacuum.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Dave Grohl recorded the Foo Fighters&#039; debut, &quot;Foo Fighters,&quot; by himself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "medium",
            "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Art",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The Statue of Liberty&#039;s official name is &ldquo;Liberty Enlightening the World&rdquo;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "hard",
            "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The shotgun appears in every numbered Resident Evil game.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ],
}
